#!/usr/bin/env python3
"""Version-bound, scope-bound handoff checks. No writes to Yunxiao or Git.

Canonical source: skills/YunxiaoPM/scripts/handoff_gate.py. Distribution copies
are generated by scripts/sync-handoff-gate.py, never imported across installs.
Hashes prove consistency, not human understanding or the truth of test claims.
Live adapters must read authoritative work items and their actual test evidence.
"""
from __future__ import annotations

import argparse
import hashlib
import html
import json
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Callable
from urllib.parse import urlparse
from urllib.request import urlopen

MANIFEST_SCHEMA = "oneos.delivery-handoff/v1"
RECEIPT_SCHEMA = "oneos.handoff-receipt/v1"
BUNDLE_SCHEMA = "oneos.handoff-evidence/v1"
SCOPE_KEYS = ("projectId", "requirementId", "deliveryId", "scopeId")
REQUIRED_KINDS = {"product-contract", "acceptance", "engineering-decisions"}
STAGES = {"development", "qa-start", "qa-complete", "release"}
SHA = re.compile(r"^[a-f0-9]{64}$")
MAX_DOCUMENT_BYTES = 10 * 1024 * 1024


def _require(ok: Any, message: str) -> None:
    if not ok:
        raise ValueError("交棒门禁：" + message)


def _text(value: Any) -> bool:
    return isinstance(value, str) and bool(value.strip()) and value.strip().lower() not in {
        "none", "null", "n/a", "待补", "待确认", "...", "无", "unknown"}


def seal(value: dict[str, Any]) -> dict[str, Any]:
    result = {k: v for k, v in value.items() if k != "sha256"}
    raw = json.dumps(result, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return {**result, "sha256": hashlib.sha256(raw.encode("utf-8")).hexdigest()}


def _sealed(value: Any, schema: str) -> None:
    _require(isinstance(value, dict), f"缺少 {schema}")
    _require(value.get("schemaVersion") == schema, f"schema 必须为 {schema}")
    _require(value.get("sha256") == seal(value)["sha256"], f"{schema} 内容哈希不一致")


def _ids(values: Any, label: str, nonempty: bool = True) -> list[str]:
    _require(isinstance(values, list), f"{label} 必须显式提供数组")
    _require(not nonempty or values, f"{label} 不能为空")
    _require(all(_text(v) for v in values), f"{label} 含无效值")
    _require(len(set(values)) == len(values), f"{label} 存在重复项")
    return values


def validate_manifest(manifest: Any, expected_scope: dict | None = None) -> dict:
    _sealed(manifest, MANIFEST_SCHEMA)
    for key in ("handoffId", "version"):
        _require(_text(manifest.get(key)), f"manifest.{key} 缺失")
    scope = manifest.get("scope")
    _require(isinstance(scope, dict), "manifest.scope 缺失")
    for key in SCOPE_KEYS:
        _require(_text(scope.get(key)), f"manifest.scope.{key} 缺失")
    for key, value in (expected_scope or {}).items():
        if key in SCOPE_KEYS:
            _require(scope.get(key) == value, f"scope.{key} 与当前工作项不一致")
    docs = manifest.get("documents")
    _require(isinstance(docs, list) and docs, "documents 不能为空")
    _require(all(isinstance(d, dict) for d in docs), "documents 格式错误")
    _ids([d.get("id") for d in docs], "documents.id")
    for doc in docs:
        _require(type(doc.get("required")) is bool, "document.required 必须显式为布尔值")
        _require(_text(doc.get("kind")), "document.kind 缺失")
        uri = urlparse(str(doc.get("uri") or ""))
        _require(uri.scheme in {"http", "https"} and uri.netloc and not uri.username
                 and not uri.password, "document.uri 必须是无凭据的团队可读 HTTP(S) 地址")
        _require(bool(SHA.fullmatch(str(doc.get("sha256") or ""))), "document.sha256 无效")
    _require(REQUIRED_KINDS <= {d["kind"] for d in docs if d["required"]},
             "必读资料须覆盖产品合同、验收标准和工程决策清单")
    _ids(manifest.get("requiredAcceptanceIds"), "requiredAcceptanceIds")
    _ids(manifest.get("requiredDecisionIds"), "requiredDecisionIds")
    _ids(manifest.get("exclusions"), "exclusions", False)
    return manifest


def validate_receipt(receipt: Any, manifest: dict, role: str,
                     task_id: str | None = None, stage: str = "development") -> dict:
    _sealed(receipt, RECEIPT_SCHEMA)
    _require(receipt.get("role") == role, f"需要 {role} 理解回执")
    for key in ("taskId", "reader", "readAt", "scopeSummary", "reviewer", "reviewEvidence"):
        _require(_text(receipt.get(key)), f"{role}.{key} 缺失")
    if task_id is not None:
        _require(receipt["taskId"] == task_id, f"{role} 回执任务编号不一致")
    try:
        timestamp = datetime.fromisoformat(receipt["readAt"].replace("Z", "+00:00"))
        _require(timestamp.tzinfo is not None, "readAt 必须带时区")
    except (ValueError, TypeError) as error:
        raise ValueError("交棒门禁：readAt 不是带时区的 ISO 时间") from error
    _require(receipt.get("handoffSha256") == manifest["sha256"], f"{role} 读的是旧交棒版本")
    hashes = receipt.get("documentHashes")
    _require(isinstance(hashes, dict), f"{role}.documentHashes 缺失")
    for doc in manifest["documents"]:
        if doc["required"] or doc["id"] in hashes:
            _require(hashes.get(doc["id"]) == doc["sha256"], f"{role} 未按当前版本读取 {doc['id']}")
    _require(set(hashes) <= {d["id"] for d in manifest["documents"]}, "回执包含未登记资料")
    _require(set(_ids(receipt.get("acceptanceIds"), "receipt.acceptanceIds")) ==
             set(manifest["requiredAcceptanceIds"]), f"{role} 未覆盖本范围全部必要验收项")
    _require(_ids(receipt.get("exclusions"), "receipt.exclusions", False) == manifest["exclusions"],
             f"{role} 未复核不做项")
    decisions = receipt.get("engineeringDecisions")
    _require(isinstance(decisions, list) and decisions and all(isinstance(d, dict) for d in decisions),
             f"{role} 缺工程决策检查；不涉及也须提供带理由的 NOT_APPLICABLE")
    decision_ids = _ids([d.get("id") for d in decisions], "engineeringDecisions.id")
    _require(set(decision_ids) == set(manifest["requiredDecisionIds"]),
             f"{role} 未覆盖冻结的工程决策检查项")
    phase = "qa" if stage.startswith("qa-") else stage
    for decision in decisions:
        _require(decision.get("status") in {"CONFIRMED", "NOT_APPLICABLE", "PENDING"},
                 "工程决策状态无效")
        for key in ("owner", "conclusion"):
            _require(_text(decision.get(key)), f"工程决策 {decision['id']} 缺 {key}")
        blocks = _ids(decision.get("blockingStages"), "blockingStages", False)
        _require(set(blocks) <= {"development", "qa", "release"}, "未知 blockingStages")
        if decision["status"] == "PENDING":
            _require(blocks, "PENDING 必须明确阻断阶段，不得留空绕过")
            _require(phase not in blocks, f"工程决策 {decision['id']} 仍为 PENDING，阻断 {phase}")
        else:
            _require(_text(decision.get("evidence")), f"工程决策 {decision['id']} 缺确认/不适用依据")
    return receipt


def validate_bundle(bundle: Any, stage: str, expected_scope: dict | None = None,
                    delivery_version: str | None = None) -> dict:
    _require(stage in STAGES, "未知验证阶段")
    _require(isinstance(bundle, dict) and bundle.get("schemaVersion") == BUNDLE_SCHEMA,
             f"缺少 {BUNDLE_SCHEMA}")
    manifest = validate_manifest(bundle.get("manifest"), expected_scope)
    _require(_text(bundle.get("deliveryVersion")), "缺少精确交付代码版本")
    if delivery_version is not None:
        _require(bundle["deliveryVersion"] == delivery_version, "交棒与当前交付代码版本不一致")
    validate_receipt(bundle.get("developmentReceipt"), manifest, "development", stage=stage)
    if stage != "development":
        validate_receipt(bundle.get("qaReceipt"), manifest, "qa", stage=stage)
    if stage in {"qa-complete", "release"}:
        result = bundle.get("qaResult")
        _require(isinstance(result, dict) and result.get("formal") is True,
                 "缺少正式 QA 结果；手工完成 formal:false 不可作为测试通过")
        _require(result.get("environment") == "test", "原型或开发自测不能替代真实测试环境证据")
        _require(result.get("deliveryVersion") == bundle["deliveryVersion"], "QA 测试的不是当前交付版本")
        for key in ("executionId", "evidence"):
            _require(_text(result.get(key)), f"qaResult.{key} 缺失")
        cases = result.get("cases")
        _require(isinstance(cases, list) and cases and all(isinstance(c, dict) for c in cases),
                 "缺少逐项验收结果")
        actual = _ids([c.get("acceptanceId") for c in cases], "qaResult.cases.acceptanceId")
        _require(set(actual) == set(manifest["requiredAcceptanceIds"]), "必要验收项漏测或测试范围错配")
        for case in cases:
            _require(case.get("result") == "PASS" and _text(case.get("evidence")),
                     f"验收项 {case['acceptanceId']} 未通过或缺真实执行证据")
    return bundle


def _read_block(description: str, name: str) -> dict | None:
    start, end = f"<!-- {name}_START -->", f"<!-- {name}_END -->"
    source = html.unescape(description or "")
    if start not in source and end not in source:
        return None
    _require(source.count(start) == 1 and source.count(end) == 1, f"{name} 重复或不完整")
    body = source.split(start, 1)[1].split(end, 1)[0].strip()
    _require(source.index(start) < source.index(end), f"{name} 顺序错误")
    if body.startswith("<!--") and body.endswith("-->"):
        body = body[4:-3].strip()
    try:
        value = json.loads(body)
    except (ValueError, TypeError) as error:
        raise ValueError(f"交棒门禁：{name} JSON 损坏") from error
    _require(isinstance(value, dict), f"{name} 必须是对象")
    return value


def _upsert_block(description: str, name: str, value: dict) -> str:
    _read_block(description, name)  # refuse corrupt/duplicate blocks; never erase them silently
    raw = json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    # Protect comment delimiters while keeping JSON round-trippable.
    raw = raw.replace("<", "\\u003c").replace(">", "\\u003e").replace("&", "\\u0026")
    start, end = f"<!-- {name}_START -->", f"<!-- {name}_END -->"
    block = f"{start}\n<!-- {raw} -->\n{end}"
    pattern = re.compile(re.escape(start) + r".*?" + re.escape(end), re.S)
    if start in (description or ""):
        return pattern.sub(lambda _: block, description, count=1)
    return ((description or "").rstrip() + "\n\n" + block).lstrip("\n")


def upsert_manifest(description: str, manifest: dict) -> str:
    validate_manifest(manifest)
    store = _read_block(description, "ONEOS_DELIVERY_HANDOFF") or {"manifests": []}
    existing = store.get("manifests")
    _require(isinstance(existing, list), "manifests 必须是数组")
    for item in existing:
        validate_manifest(item)
    values = [m for m in existing if m["scope"] != manifest["scope"]] + [manifest]
    return _upsert_block(description, "ONEOS_DELIVERY_HANDOFF", {"manifests": values})


def manifest_from_description(description: str, scope: dict) -> dict:
    store = _read_block(description, "ONEOS_DELIVERY_HANDOFF")
    _require(isinstance(store, dict) and isinstance(store.get("manifests"), list), "云效缺少当前交棒清单")
    matches = [m for m in store["manifests"] if isinstance(m, dict) and
               all(m.get("scope", {}).get(k) == v for k, v in scope.items() if k in SCOPE_KEYS)]
    _require(len(matches) == 1, "交棒 scope 无法唯一匹配")
    return validate_manifest(matches[0], scope)


def upsert_bundle(description: str, bundle: dict) -> str:
    _require(isinstance(bundle, dict) and bundle.get("schemaVersion") == BUNDLE_SCHEMA, "bundle schema 无效")
    return _upsert_block(description, "ONEOS_HANDOFF_EVIDENCE", bundle)


def bundle_from_description(description: str) -> dict:
    value = _read_block(description, "ONEOS_HANDOFF_EVIDENCE")
    _require(value is not None and value.get("schemaVersion") == BUNDLE_SCHEMA, "云效未回读交棒理解回执")
    return value


def verify_live_bundle(bundle: dict, stage: str, read_workitem: Callable[[str], dict],
                       expected_scope: dict | None = None, delivery_version: str | None = None) -> dict:
    validate_bundle(bundle, stage, expected_scope, delivery_version)
    manifest = bundle["manifest"]
    scope = manifest["scope"]
    def read(item_id):
        item = read_workitem(item_id)
        _require(isinstance(item, dict) and str(item.get("id")) == item_id,
                 "官方回读工作项身份不一致")
        return str(item.get("description") or "")
    for item_id in (scope["requirementId"], scope["deliveryId"]):
        live = manifest_from_description(read(item_id), scope)
        _require(live == manifest, "产品交棒已经换版或需求/交付两边不一致，须重读并重新复核")
    if stage != "development":
        dev = bundle_from_description(read(bundle["developmentReceipt"]["taskId"]))
        validate_bundle(dev, "development", scope, bundle["deliveryVersion"])
        _require(dev["manifest"] == manifest and dev["developmentReceipt"] == bundle["developmentReceipt"],
                 "开发理解回执未落盘、已过期或被替换")
    if stage == "release":
        qa = bundle_from_description(read(bundle["qaReceipt"]["taskId"]))
        validate_bundle(qa, "qa-complete", scope, bundle["deliveryVersion"])
        _require(qa == bundle, "当前 QA 工作项中的正式结果与发布输入不一致")
    return bundle


def read_document(doc: dict) -> bytes:
    with urlopen(doc["uri"], timeout=20) as response:
        _require(response.status == 200, f"必读资料 {doc['id']} 无法读取")
        content = response.read(MAX_DOCUMENT_BYTES + 1)
    _require(0 < len(content) <= MAX_DOCUMENT_BYTES, f"资料 {doc['id']} 为空或超过 10 MiB")
    return content


def verify_documents(manifest: dict, reader: Callable[[dict], bytes] | None = None) -> dict:
    validate_manifest(manifest)
    loader = reader or read_document
    hashes = {}
    for doc in manifest["documents"]:
        if doc["required"]:
            digest = hashlib.sha256(loader(doc)).hexdigest()
            _require(digest == doc["sha256"], f"资料 {doc['id']} 实际内容与冻结版本不一致")
            hashes[doc["id"]] = digest
    return hashes


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("verify", "seal"))
    parser.add_argument("--input", required=True)
    parser.add_argument("--stage", choices=sorted(STAGES), default="development")
    parser.add_argument("--output")
    args = parser.parse_args()
    try:
        value = json.loads(Path(args.input).read_text(encoding="utf-8-sig"))
        if args.command == "seal":
            value = seal(value)
            if value.get("schemaVersion") == MANIFEST_SCHEMA:
                verify_documents(value)
            else:
                _require(value.get("schemaVersion") == RECEIPT_SCHEMA, "只能封存清单或理解回执")
        else:
            validate_bundle(value, args.stage)
            verify_documents(value["manifest"])
            value = {"result": "passed", "stage": args.stage,
                     "handoffSha256": value["manifest"]["sha256"],
                     "boundary": "本地内容一致性校验；不等于官方回读、人类理解或生产授权"}
        if args.output:
            Path(args.output).write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(json.dumps(value, ensure_ascii=False, indent=2))
        return 0
    except (ValueError, OSError) as error:
        print(json.dumps({"result": "blocked", "error": str(error)}, ensure_ascii=False))
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
